# Generated by Django 3.0.8 on 2020-09-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_used_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]

