# Generated by Django 3.0.8 on 2020-09-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200918_1645'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
    
