# Generated by Django 3.0.8 on 2020-09-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200918_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetext',
            name='heading',
            field=models.TextField(blank=True),
        ),
    ]

