# Generated by Django 3.0.8 on 2020-09-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_comment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
    ]
